server:
        port: 8085

spring:
    mvc:
        pathmatch:
                  matching-strategy: ant_path_matcher

    datasource:
         driver-class-name: com.mysql.cj.jdbc.Driver
         url: jdbc:mysql://localhost:3306/mikemopo
         username: root
         password: password

    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
        properties:
                  hibernate:
                      dialect: org.hibernate.dialect.MySQL5Dialect